blank_issues_enabled: false

contact_links:
  - name: 💬 Discussion / Questions
    url: https://github.com/firaseth/reach-os/discussions
    about: Please ask general questions in GitHub Discussions rather than opening an issue.
